/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as TemporalRouteImport } from './routes/temporal'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MachineLearningRouteImport } from './routes/machine-learning'
import { Route as GeografiaRouteImport } from './routes/geografia'
import { Route as ConclusoesRouteImport } from './routes/conclusoes'
import { Route as IndexRouteImport } from './routes/index'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporalRoute = TemporalRouteImport.update({
  id: '/temporal',
  path: '/temporal',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineLearningRoute = MachineLearningRouteImport.update({
  id: '/machine-learning',
  path: '/machine-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const GeografiaRoute = GeografiaRouteImport.update({
  id: '/geografia',
  path: '/geografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusoesRoute = ConclusoesRouteImport.update({
  id: '/conclusoes',
  path: '/conclusoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conclusoes': typeof ConclusoesRoute
  '/geografia': typeof GeografiaRoute
  '/machine-learning': typeof MachineLearningRoute
  '/perfil': typeof PerfilRoute
  '/temporal': typeof TemporalRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conclusoes': typeof ConclusoesRoute
  '/geografia': typeof GeografiaRoute
  '/machine-learning': typeof MachineLearningRoute
  '/perfil': typeof PerfilRoute
  '/temporal': typeof TemporalRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conclusoes': typeof ConclusoesRoute
  '/geografia': typeof GeografiaRoute
  '/machine-learning': typeof MachineLearningRoute
  '/perfil': typeof PerfilRoute
  '/temporal': typeof TemporalRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conclusoes'
    | '/geografia'
    | '/machine-learning'
    | '/perfil'
    | '/temporal'
    | '/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conclusoes'
    | '/geografia'
    | '/machine-learning'
    | '/perfil'
    | '/temporal'
    | '/veiculos'
  id:
    | '__root__'
    | '/'
    | '/conclusoes'
    | '/geografia'
    | '/machine-learning'
    | '/perfil'
    | '/temporal'
    | '/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConclusoesRoute: typeof ConclusoesRoute
  GeografiaRoute: typeof GeografiaRoute
  MachineLearningRoute: typeof MachineLearningRoute
  PerfilRoute: typeof PerfilRoute
  TemporalRoute: typeof TemporalRoute
  VeiculosRoute: typeof VeiculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporal': {
      id: '/temporal'
      path: '/temporal'
      fullPath: '/temporal'
      preLoaderRoute: typeof TemporalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-learning': {
      id: '/machine-learning'
      path: '/machine-learning'
      fullPath: '/machine-learning'
      preLoaderRoute: typeof MachineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geografia': {
      id: '/geografia'
      path: '/geografia'
      fullPath: '/geografia'
      preLoaderRoute: typeof GeografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusoes': {
      id: '/conclusoes'
      path: '/conclusoes'
      fullPath: '/conclusoes'
      preLoaderRoute: typeof ConclusoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConclusoesRoute: ConclusoesRoute,
  GeografiaRoute: GeografiaRoute,
  MachineLearningRoute: MachineLearningRoute,
  PerfilRoute: PerfilRoute,
  TemporalRoute: TemporalRoute,
  VeiculosRoute: VeiculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
